"""CameraE2E v2 research project and decision platform."""

from .calibration import calibration_pack_status
from .catalog import seed_builtin_camera_assets
from .engine import CameraEngine, FidelityRouter
from .evaluation import StudyEvaluator
from .models import (
    ArtifactRecord,
    AssetKind,
    BenchmarkPreflightResult,
    BenchmarkSuite,
    CalibrationRequest,
    CameraAssetRecord,
    CameraModule,
    CandidateEvidenceState,
    CandidatePromotionResult,
    ComponentSelection,
    Constraint,
    DesignVariable,
    FidelityLevel,
    FidelityPolicy,
    GeometryTransform,
    ISPConfig,
    JobRecord,
    JobStatus,
    LensConfig,
    ModuleBaselineRequest,
    ModuleCompareRequest,
    ModuleEvaluationRequest,
    Objective,
    ProjectInfo,
    Quantity,
    ReadinessTier,
    RequirementGateResult,
    RequirementSet,
    RobustnessCase,
    SceneAggregateMetrics,
    SceneCase,
    SensorConfig,
    StudyCreate,
    StudyRecord,
)
from .project import Project, ProjectManager
from .service import CameraE2EService
from .storage import ArtifactRegistry, ProjectStore

__all__ = [
    "ArtifactRecord",
    "ArtifactRegistry",
    "AssetKind",
    "BenchmarkPreflightResult",
    "BenchmarkSuite",
    "calibration_pack_status",
    "CalibrationRequest",
    "CameraEngine",
    "CameraAssetRecord",
    "CameraE2EService",
    "CameraModule",
    "CandidateEvidenceState",
    "CandidatePromotionResult",
    "Constraint",
    "ComponentSelection",
    "DesignVariable",
    "FidelityLevel",
    "FidelityPolicy",
    "FidelityRouter",
    "GeometryTransform",
    "ISPConfig",
    "JobRecord",
    "JobStatus",
    "LensConfig",
    "ModuleBaselineRequest",
    "ModuleCompareRequest",
    "ModuleEvaluationRequest",
    "Objective",
    "Project",
    "ProjectInfo",
    "ProjectManager",
    "ProjectStore",
    "Quantity",
    "ReadinessTier",
    "RequirementSet",
    "RequirementGateResult",
    "RobustnessCase",
    "SceneCase",
    "SensorConfig",
    "SceneAggregateMetrics",
    "seed_builtin_camera_assets",
    "StudyCreate",
    "StudyEvaluator",
    "StudyRecord",
]
